version: '3.9'

services:
  mysqldb:
    image: mysql:8.0
    restart: "always"
    environment:
      MYSQL_ROOT_PASSWORD: 'sigma12345'
      MYSQL_ROOT_HOST: '%'  # needs to be enclosed with quotes
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./initialize_db/init.sql:/data/application/init.sql:rw,delegated
    healthcheck:
      test: ["CMD-SHELL", "mysql --user=root --password=$${MYSQL_ROOT_PASSWORD} --execute=\"SHOW DATABASES;\""]
      timeout: 20s
      retries: 10
    platform: linux/amd64
  booking-api:
    restart: "always"
    depends_on:
      mysqldb:
        condition: service_completed_successfully
    build: .
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_PASS=sigma12345
      - JWT_SECRET_KEY=superSecretKey
volumes:
  mysql-data:
