version: '3.9'

services:
  mysqldb:
    image: mysql:8.0.26
    restart: "always"
    environment:
      MYSQL_ROOT_PASSWORD: 'sigma12345'
      MYSQL_ROOT_HOST: '%' # needs to be enclosed with quotes
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./initialize_db:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost" ]
      timeout: 20s
      retries: 10
    platform: linux/amd64
    command: --init-file=/docker-entrypoint-initdb.d/init.sql
  booking-api:
    restart: "always"
    depends_on:
      mysqldb:
        condition: service_healthy
    build: .
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_PASS=sigma12345
      - JWT_SECRET_KEY=superSecretKey
volumes:
  mysql-data:
