version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root12345
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
      # - ./initialize_db:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  booking-api:
    depends_on:
      - mysqldb
    build: .
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - DB_HOST=127.0.0.1
      - DB_USER=root
      - DB_PASS=sigma12345
      - JWT_SECRET_KEY=superSecretKey
volumes:
  mysql-data:
